/** 手势识别模块导出入口 */
export { ConductGuideCard } from './components/ConductGuideCard'
export { HandAssignmentPanel } from './components/HandAssignmentPanel'
export { GestureIntentOverlay, GestureKeyboardOverlay, GestureToggle } from './components/GesturePanel'
export { HandOverlay } from './components/HandOverlay'
export { useCamera } from './hooks/useCamera'
export { useMediaPipeHands } from './hooks/useMediaPipeHands'
export { useGestureAnalyzer } from './hooks/useGestureAnalyzer'
export type { GestureStatus, HandFrame } from './types'
export type { HandFeatures, AnalyzerSnapshot } from './lib/analyzer/types'
export type { IntentEvent, IntentType } from './lib/intent/types'
export { INTENT_LABELS } from './lib/intent/types'
export { GestureAnalyzer } from './lib/analyzer/extractHandFeatures'
export { IntentDetector } from './lib/intent/intentDetector'
